---
# php tasks/php.yaml

- name: Include variables for php 8.2
  ansible.builtin.include_vars:
    file: php82.yaml
  when: php_version == 8.2
  tags:
    - php
    - php.php
    - php.variables
    - php.php82_variables

- name: Include variables for php 7.4
  ansible.builtin.include_vars:
    file: php74.yaml
  when: php_version == 7.4
  tags:
    - php
    - php.php
    - php.variables
    - php.php74_variables

- name: Install remi-repo (local dev only)
  import_tasks: remi_repo.yaml
  when: php_install_remi_repo is true
  tags:
    - php
    - php.php
    - php.remi_repo

- name: Set php version to use (dnf module)
  ansible.builtin.template:
    src: php.module.j2
    dest: /etc/dnf/modules.d/php.module
    owner: root
    group: root
    mode: 0644
  when: php_use_module
  tags:
    - php
    - php.php
    - php.set_php_module_version

- name: Install php packages
  ansible.builtin.package:
    name: "{{ php_packages_to_install }}"
    state: present
  notify:
    - restart apache
  when: not ansible_check_mode
  tags:
    - php
    - php.php
    - php.install_php

# This is for when we install phpX-php packages (when not using the module)
- name: symlink cli phpXX to /usr/bin/php
  ansible.builtin.file:
    src: "{{ php_symlink_to }}"
    dest: /usr/bin/php
    owner: root
    group: root
    state: link
  when: php_symlink_cli
  tags:
    - php
    - php.php
    - php.symlink_cli

- name: Create /var/log/php-fpm directory
  ansible.builtin.file:
    path: /var/log/php-fpm
    state: directory
    owner: apache
    group: root
    mode: 0770
  tags:
    - php
    - php.php
    - php.create_php_fpm_log_directory

- name: Deploy php-fpm pool config www.conf
  ansible.builtin.template:
    src: "{{ php_fpm_pool_template }}"
    dest: "{{ php_etc_dir }}/php-fpm.d/www.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    restart php-fpm
  tags:
    - php
    - php.php
    - php.deploy_fpm_www_conf

- name: Deploy server-status / php-fpm status config
  ansible.builtin.template:
    src: "z-status.conf.j2"
    dest: "/etc/httpd/conf.d/z-status.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    - restart apache
  tags:
    - php
    - php.php
    - php.deploy_apache_fpm_status_config

- name: Deploy index.php
  ansible.builtin.copy:
    src: "index.php"
    dest: "/var/www/html/index.php"
    mode: 0644
    owner: root
    group: root
  tags:
    - php
    - php.php
    - php.install_index_php

- name: Enable php-fpm service
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    enabled: yes
    state: started
  when: not ansible_check_mode
  tags:
    - php
    - php.php
    - php.enable_fpm_service
