---
# php tasks/php.yaml

- name: Include variables for php 8.2
  ansible.builtin.include_vars:
    file: php82.yaml
  when: php_version == 8.2
  tags:
    php
    php.php82_variables

- name: Include variables for php 7.4
  ansible.builtin.include_vars:
    file: php74.yaml
  when: php_version == 7.4
  tags:
    php
    php.php74_variables

- name: Install remi-repo (local dev only)
  import_tasks: remi_repo.yaml
  when: php_install_remi_repo is true
  tags:
    php
    php.remi_repo

- name: Install php-fpm
  ansible.builtin.package:
    name: php-fpm
    state: present
  notify:
    - restart apache
  tags:
    php
    php.install_php_fpm

- name: Deploy index.php
  ansible.builtin.copy:
    src: "index.php"
    dest: "/var/www/html/index.php"
    mode: 0644
    owner: root
    group: root
  tags:
    php
    php.install_index_php

- name: Enable php-fpm service
  ansible.builtin.service:
    name: php-fpm
    enabled: yes
    state: started
  tags:
    php
    php.enable_fpm_service
