---
# php tasks/remi_repo.yaml

- name: Copy remi repo gpg key
  ansible.builtin.copy:
    src: "{{ php_remi_repo_rpm_gpg_key_file }}"
    dest: "/etc/rpm/{{ php_remi_repo_rpm_gpg_key_file }}"
    mode: 0644
    owner: root
    group: root
  tags:
    - php
    - php.remirepo
    - php.remirepo.deploy_gpg_key

- name: Import remi gpg key
  ansible.builtin.rpm_key:
    key: "/etc/rpm/{{ php_remi_repo_rpm_gpg_key_file }}"
    state: present
  tags:
    - php
    - php.remirepo
    - php.remirepo.import_gpg_key

- name: Install remi-repo
  ansible.builtin.dnf:
    name: "{{ php_remi_repo }}"
    state: present
  tags:
    - php
    - php.remirepo
    - php.remirepo.install_remirepo
