---
# php handlers.yaml

- name: restart apache
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: restart php-fpm
  ansible.builtin.service:
    name: php-fpm
    state: restarted

- name: systemd daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
